CURRENT_POSITION_COL = "current_position"
POSITION_DELTA_COL = "position_delta"
TARGET_DOLLAR_POSITION_COL = "target_dollar_position"
CURRENT_DOLLAR_POSITION_COL = "current_dollar_position"
TRADE_COL = "trade"

TRADE_COLUMNS = [
    CURRENT_POSITION_COL,
    POSITION_DELTA_COL,
    TARGET_DOLLAR_POSITION_COL,
    CURRENT_DOLLAR_POSITION_COL,
    TRADE_COL,
]
